### ISSUE TITLE
Rule: `sprintf-arguments-mismatch`

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#1009]
If too many or too few arguments are in the array provided to `sprintf`, OPA will return the "error" back in the string created.
```
> opa eval -f raw 'sprintf("%v", [1,2,3])'
1%!(EXTRA int=2, int=3)
```
```
opa eval -f raw 'sprintf("%v", [])'
%!v(MISSING)
```
It would be helpful if Regal did a count of the args in the string and compared it to the number of args in the array provided (if known), and flagged this as an issue.

**Comment by srenatus** [comment]
```
% opa eval -f raw 'sprintf("%[1]v %[1]s", ["foo"])'
foo foo
```

It's annoying to fix this because we haven't specified what's OK and what is not, and the surface is just so large. But covering the 80% would certainly be useful.

**Comment by anderseknert** [comment]
Yeah, good point! I'd say covering the "normal" cases is probably going to amount to somewhere closer to 99%... but perhaps people are more creative with `sprintf` than what I've seen.

Both "explicit argument indexes" (of which I learnt about just now), and `%%` which means "literally %" should be possible to account for... but perhaps there are more ways to have `%` not necessarily map 1:1 to a value.
