### ISSUE TITLE
panic parsing metadata during server initialization

### ISSUE THREAD

**Issue by frittsy** [StyraInc/regal#1089]
Getting the following error when launching the server within VS Code. On `0.26.1` of Regal, `0.68.0` of OPA, so latest.

```
Server initialization failed.
Message: failed to load workspace contents: failed to walk workspace dir "/path/to": failed to update parse: failed to update rego store with parsed module: failed to marshal module to JSON: ReadMapCB: object not ended with }, error found in #10 byte of ...|":"value""example":"|..., bigger context ...|IyAgIH0=","scope":"rule","custom":{"attr":"value""example":"resource \"aws_resource\" \"this\" {\n  |...
```

Seems to be related to parsing metadata of an usual format, here's a minimal example:
```rego
package something

# METADATA
# custom:
#  attr: value
#  example: |
#   resource "aws_resource" "this" {
#     attr = "value"
#   }
this := true
```

Let me know if there's any other info that would be helpful.

**Comment by anderseknert** [comment]
Hi Luke! 👋 And thanks for letting us know! 

This is issue #1082 rearing its head in the language server, as every file in the workspace will be linted on launch. It’s been fixed, and v0.26.2 will be published today including that and some other fixes.

**Comment by anderseknert** [comment]
Fixed in #1087. Sorry for the inconvenience! v0.26.2 to be released later today.

**Comment by frittsy** [comment]
Whoops, my issue searching failed me, sorry for the dupe.

Thanks for the quick fix!

**Comment by anderseknert** [comment]
No worries! I'd rather see duplicate issues than no one reporting. v0.26.2 is out now :)
