### ISSUE TITLE
lint: Suggestion - issues with error levels in output

### ISSUE THREAD

**Issue by geirs73** [StyraInc/regal#1211]
Context: We have a build pipeline where we check our bundle in many ways before accepting it for upload to our Styra systems.

Problem: Pretty-formatted output on console is colored red for errors, but when running with `--no-colors` they are indistinguishable from warnings. Of course, that is the way we see it in our build server logs.  

Mitigation: My workaround is to use `--format github` instead, since level is visible there. 

Suggestion: Maybe the combination `--format pretty --no-colors` should have some extra information outputted, either another line with level, or a bracket after the description, [warning] or [error]

Suggestion: Another possibility is to filter output based on level, by specifying `--level (warning|error)`.  That way, you can prioritize to only see errors. Alternatively, it could be `--level (ignore|warning|error)` so that you can see how many ignored rules are affected without having to cheat with different config files. However, when developing rules, we work in vscode-opa extension, so I'm not sure this is needed, as they show up in the Problems panel view. Yes, it would also solve my build server problem, but I would like to see both warnings and errors there.

Regal version info:
```text
Version:    0.28.0
Go Version: go1.22.5
Platform:   windows/amd64
Commit:     9503967b3cd1d3725d078b04dd55ee9ec807b3f3
Timestamp:  2024-10-07T15:17:16Z
Hostname:   github.actions.local
````

**Comment by charlieegan3** [comment]
Hey @geirs73, lmk if the impl at https://github.com/StyraInc/regal/pull/1213 looks suitable for your use case!

**Comment by geirs73** [comment]
Thanks @charlieegan3 ! This looks great. Just tested it on a locally built version.

**Comment by charlieegan3** [comment]
That's great, glad to hear it! we should be getting a release out within the next week or so.
