### ISSUE TITLE
Invalid use-contains violation?

### ISSUE THREAD

**Issue by drewcorlin1** [StyraInc/regal#1212]
I just upgraded to regal v0.28.0 and am seeing (what I think are) false positives on the use-contains rule. I'm using OPA 0.44.0 if that's relevant.

I customize my logs via
```regal
package system.log

import future.keywords.contains

mask contains "/input/attributes/request/http/headers/authorization"
```

And when running `regal lint` on that file it's telling me
```
Rule:         	use-contains                                                        	
Description:  	Use the `contains` keyword                                          	
Category:     	idiomatic                                                           	
Location:     	policies/logging.rego:5:1                                           	
Text:         	mask contains "/input/attributes/request/http/headers/authorization"	
Documentation:	https://docs.styra.com/regal/rules/idiomatic/use-contains 
```

I've set that line to 
`mask["/input/attributes/request/http/headers/authorization"]` and then run `opa fmt --write` on it and it corrects it to what I put above, then regal still says its incorrect.

**Comment by anderseknert** [comment]
Thanks for reporting that! 👍  Looks like a bug indeed. I'll take a look.

**Comment by drewcorlin1** [comment]
thanks so much!

**Comment by anderseknert** [comment]
Turned out to be a bug in OPA, so bonus points to you for finding and reporting it 🙂 The fix is merged, but we'll have to wait until the next OPA release before we pull that in. I'll keep this open until we do, so we don't forget to verify.
