### ISSUE TITLE
inconsistent-args rule does not handle wildcard variables correctly

### ISSUE THREAD

**Issue by tsandall** [StyraInc/regal#1250]
:wave:

[NOTE: I originally opened this because I thought there was a bug with wildcard handling, but it looks like arity mismatches are the problem.]

It seems that arity mismatches cause the rule to report incorrectly.

```
matches_category(pod, category, app_labels) if {
    category != "none"
    pod.metadata.labels.app in app_labels
}

# regal reports a problem on this line
matches_category(pod, "none", _) if {
    not pod.metadata.labels.app
}

matches_category(pod, app_labels) if {
    not pod.metadata.labels.app in app_labels
}
```

**Comment by anderseknert** [comment]
Yeah, looks like we've left the arity check to the compiler. Which is fine, I think, as we don't want to duplicate the work that's doing here... but obviously, we shouldn't report that as a false positive. I'll take a look.
