### ISSUE TITLE
Example about aggregate rules seems not to work correctly

### ISSUE THREAD

**Issue by shibataka000** [StyraInc/regal#1259]
## Summary

Example about aggregate rules on https://docs.styra.com/regal/custom-rules#aggregate-rules seems not to work correctly.

### What happened?

I created a new repository https://github.com/shibataka000/regal-example and copied following custom rules on https://docs.styra.com/regal/custom-rules .

- [`acme-corp-package`](https://docs.styra.com/regal/custom-rules#developing-rules)
- [`at-least-one-allow`](https://docs.styra.com/regal/custom-rules#aggregate-rules)

AFAIK, custom rule `at-least-one-allow` reports error if there is no rule whose name is `allow` and whose default value is `false`.

I ran following command.

```bash
regal lint .
```

Regal reports no error although there is no rule whose name is `allow` and whose default value is `false`.

### What I expected to happen?

I expected that regal reports error about custom rule `at-least-one-allow` because there is no rule whose name is `allow` and whose default value is `false`.

## How to reproduce the issue

```bash
git clone https://github.com/shibataka000/regal-example
cd regal-example/
regal lint .
```

## Version

```bash
$ opa version
Version: 0.70.0
Build Commit: 2ea031ea04e6a8afbc5dd22f656131dc3cfc5a7d
Build Timestamp: 2024-10-31T19:39:52Z
Build Hostname: 799a5774bce7
Go Version: go1.23.1
Platform: linux/amd64
WebAssembly: available

$ regal version
Version:    0.29.0
Go Version: go1.22.5
Platform:   linux/amd64
Commit:     5cb67eaa310ece0a4c670390d95862f9d363c474
Timestamp:  2024-11-12T13:53:27Z
Hostname:   github.actions.local
```

**Comment by shibataka000** [comment]
Please tell me why custom rule `at-least-one-allow` does not work correctly in my case if someone know.

**Comment by anderseknert** [comment]
Hi there! And thanks for an excellent bug report 👍 I've cloned your repo and it does seem like there's an issue with custom aggregate rules. I'll report back as soon as I've found out what it could be.

**Comment by anderseknert** [comment]
That was more involved than I imagined. The issue turned out to be isolated to rules where no aggregated data was the actual violation, like in the example. Rules that actually did aggregate something first would however work as expected. I have a fix up now, and will push a patch release when that's been approved and merged.
