### ISSUE TITLE
regal fix with directory-package-mismatch assumes root as base

### ISSUE THREAD

**Issue by mrueg** [StyraInc/regal#1300]
My repository looks like this

```
.git
policy/my-opa-rule/src.rego
README.md
```

in src.rego the package is called `my_opa_rule`
when I run `rego fix policy` it detects the directory-package-mismatch 

instead of 
```
.git
policy/my_opa_rule/src.rego
README.md
```

it creates the following structure:
```
.git
my_opa_rule/src.rego
policy
README.md
```

possible solution:

`rego fix $path` should include $path when fixing directory package mismatches.

**Comment by anderseknert** [comment]
Hi there! And thanks for raising this.

I think it’s referenced in the docs for regal fix, but we should add a link from the docs of that rule too. You can set the project roots either via configuration, or by using .manifest files https://docs.styra.com/regal#project-roots

**Comment by mrueg** [comment]
Thanks for the quick response! It was kinda unexpected when running the fix. I assumed base/root defaults to the path supplied, good to know!

**Comment by anderseknert** [comment]
Yeah, that would work well for some commands, and others not so much, as e.g the Regal config may be in a directory above. So we tend to default to where the .regal directory is… and if that’s not found, I think the behavior differs some between commands, and  if invoked as a tool or a server, etc. Certainly room for improvement here.. :)

**Comment by anderseknert** [comment]
Reopening this to make sure we add docs about project roots (or at least a link to the docs) in the directory-package-mismatch rule docs.
