### ISSUE TITLE
JUnit output format fails: invalid memory address

### ISSUE THREAD

**Issue by OhMyGuus** [StyraInc/regal#1306]
Hey, I'm trying to use the JUnit output, but for some reason, it fails with a memory error.
Tried other formats and those are working fine.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf2245c]

goroutine 1 [running]:
github.com/styrainc/regal/pkg/reporter.JUnitReporter.Publish({{0x1943a20?, 0xc0000a6028?}}, {0xc000b08ef8?, 0xc000a2e5c0?}, {0x0, 0x0, 0x0, 0x0, {0xc000245008, 0x28, ...}, ...})
        /home/runner/work/regal/regal/pkg/reporter/reporter.go:525 +0x85c
github.com/styrainc/regal/cmd.lint({0xc000896a80, 0x1, 0x3}, 0xc000c7d680)
        /home/runner/work/regal/regal/cmd/lint.go:341 +0x17f4
github.com/styrainc/regal/cmd.init.4.func2({0xc000896a80, 0x1, 0x3})
        /home/runner/work/regal/regal/cmd/lint.go:109 +0xb4
github.com/styrainc/regal/cmd.init.4.wrapProfiling.func3(0xc0002bf208, {0xc000896a80, 0x1, 0x3})
        /home/runner/work/regal/regal/cmd/profiling.go:16 +0x733
github.com/spf13/cobra.(*Command).execute(0xc0002bf208, {0xc000896a20, 0x3, 0x3})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0x222b560)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0x0?)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041 +0x13
main.main()
        /home/runner/work/regal/regal/main.go:16 +0x2b
```

command used:

`` 
regal lint --format junit ./policies/claims
``

**Comment by anderseknert** [comment]
Hi there, and thanks for reporting this issue. The JUnit format is a recent contribution, and I guess not as well-tested as the others. But that's no excuse! And that's a nil dereference alright https://github.com/StyraInc/regal/blob/7f8e54d5891cd135887c71de6e85d2c65f0985d0/pkg/reporter/reporter.go#L525

While I wasn't able to directly reproduce it here, what seems to happen is that you have a violation that doesn't have a corresponding text attribute, and we're trying to print something that doesn't exist. Fixing.

**Comment by anderseknert** [comment]
PR is up and the fix will be included in the next release. Might be that's after the holidays though, so if you want, you can download a binary with the fix from the PR build. You'll find the artifacts in the bottom of this page https://github.com/StyraInc/regal/actions/runs/12400026924

(There's no Windows build there though, for reasons I don't remember 😅 so if that's your platform, you'll have to `go build` yourself)

**Comment by OhMyGuus** [comment]
Thanks a lot for the fast response, seems to work fine with the new build! 👍

**Comment by anderseknert** [comment]
Awesome! May I ask what you’re using the JUnit output for? I think the contributor of that format mentioned GitLab support, but I could be wrong. Mostly just curious to learn which tools people use together with Regal, and how 🙂

**Comment by OhMyGuus** [comment]
> Awesome! May I ask what you’re using the JUnit output for? I think the contributor of that format mentioned GitLab support, but I could be wrong. Mostly just curious to learn which tools people use together with Regal, and how 🙂

We use the JUnit output in the Azure pipelines, along with the [PublishTestResults@2](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-test-results-v2) task to publish them to an overview within Azure DevOps.

**Comment by anderseknert** [comment]
Thanks! 👍
