### ISSUE TITLE
Container image

### ISSUE THREAD

**Issue by loekensgard** [StyraInc/regal#163]
Hi, 

I came across this linter project and I'm interested in incorporating it into my CI/CD pipeline. I noticed that the project is not currently available as a container image. Is there any plans to provide the linter as a container image, preferably GHCR or Docker Hub?

**Comment by anderseknert** [comment]
Hi @loekensgard 👋 We didn't make it a priority for the first release, but publishing images for those that want that makes sense to me. What CI/CD pipeline platform are you using? Any that only works with containerized tools?

Either way, we'll look into this soon.

**Comment by loekensgard** [comment]
We are using GitLab CI/CD, which supports both containerized and non-containerized workflows, however we are strictly using containers to run our pipelines 😄

**Comment by anderseknert** [comment]
Good to know! Do they have anything equivalent to GitHub actions that we might want to look into in addition to publishing images for Regal?

**Comment by charlieegan3** [comment]
This is WIP following #164, I'm just trying to press the right buttons on goreleaser.

**Comment by charlieegan3** [comment]
Example use

```
$ cat thing.rego 
package things

things {
	thing      = [1, 2, 3][_]
	thing == 4
}

$ docker run -v ${PWD}/thing.rego:/app/thing.rego -it ghcr.io/styrainc/regal:latest lint /app/thing.rego
Rule:         	opa-fmt                                                                
Description:  	File should be formatted with `opa fmt`                                
Category:     	style                                                                  
Location:     	/app/thing.rego                                                        
Documentation:	https://github.com/StyraInc/regal/blob/main/docs/rules/style/opa-fmt.md

1 file linted. 1 violation found.
```

**Comment by anderseknert** [comment]
Yay! Thanks a lot @charlieegan3 👏

**Comment by loekensgard** [comment]
Thanks a lot guys @anderseknert @charlieegan3 👏 💯 

Already tested and can confirm that it works in my pipeline.

**Comment by anderseknert** [comment]
Sweet! We should probably mention this in the README somewhere, but I’m making a note for that later.

**Comment by charlieegan3** [comment]
That's great, thanks for testing & confirming @loekensgard!

If you've any interest, it'd be great to see Intility on the [OPA adopters list](https://github.com/open-policy-agent/opa/blob/main/ADOPTERS.md) 😊
