### ISSUE TITLE
regal test reports "undefined function data.regal.result.fail"

### ISSUE THREAD

**Issue by kristiansvalland** [StyraInc/regal#196]
# Description

I am following the guide [here](https://github.com/StyraInc/regal/blob/698c78ec2cd215921c9cfbe9ceb5099f8ecb47bc/docs/custom-rules.md) for writing custom Regal lint rules. However, when I try to write tests for the custom rules stored in `.regal/rules` as described in the guide, I get the following error messages when I run `regal test`

```
$ regal test .regal/rules
2 errors occurred:
.regal/rules/guide.rego:17: rego_type_error: undefined function data.regal.result.location
.regal/rules/guide.rego:17: rego_type_error: undefined function data.regal.result.fail
```

# Expected output

Based on what I understand from the guide referenced above,

> * `regal test` works like `opa test`, but aware of any custom Regal additions. Use this to test custom linter rules

I would expect this to work out of the box.

# Reproduce reported behaviour

1. Add the example custom rule from [here](https://github.com/StyraInc/regal/blob/698c78ec2cd215921c9cfbe9ceb5099f8ecb47bc/docs/custom-rules.md) to a file `.regal/rules/guide.rego`
2. Run `regal test .regal/rules`
3. Observe output.

# Environment
* Regal version:
  ```
  Version:    0.4.0
  Go Version: go1.20.5
  Platform:   darwin/arm64
  Commit:        unknown
  Timestamp:  2023-07-04T09:02:54Z
  Hostname:   github.actions.local
  ```

**Comment by srenatus** [comment]
Thanks for reporting this!

From skimming the code, it seems like [the test code](https://github.com/StyraInc/regal/blob/main/cmd/test.go) doesn't [load the embedded rules bundle like lint does](https://github.com/StyraInc/regal/blob/main/cmd/lint.go#L181). Not an expert here, but that's what I'd try first, I think.

**Comment by anderseknert** [comment]
Sounds about right @srenatus! Thanks for reporting @kristiansvalland 👍 I believe the custom rules made no use of "extra" data or functions when they were devised, and I simply never tested them since then having too much to do around the provided rules, where `regal test bundle` have done the trick. Vacation here, but I can probably take a look at this sometime this week. Unless someone beats me to it ;)

**Comment by anderseknert** [comment]
cx

**Comment by anderseknert** [comment]
Lol, my one year old son apparently thought we could close this 😆

**Comment by kristiansvalland** [comment]
I would like to give it a shot :) I will open a PR once I have a fix and test for it. Enjoy your vacation! 🌴

**Comment by anderseknert** [comment]
Thanks Kristian!
