### ISSUE TITLE
Prefer default function to conditionless else

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#211]
Jumping the gun here :) But adding this as a reminder once the next OPA version is out, and we'll have [default functions](
https://github.com/open-policy-agent/opa/issues/2445) 🤤 Once we do, I'm inclined to say we should:

**Avoid**
```rego
package policy

city(person) := city {
    location := person.location
    city := location.city
} else := "unknown"
```

**Prefer**
```rego
package policy

default city(_) := "unknown"

city(person) := city {
    location := person.location
    city := location.city
} 
```
I'll definitely need to come up with a better example for the docs, but I hope the message is clear regardless 😄

@kristiansvalland @charlieegan3 @srenatus agreed? 

An alternative would be to file this under the "style" category, but I do think this should be considered more than that. EDIT: changed my mind. Considering this for the style category.

**Comment by anderseknert** [comment]
I guess it does raise the question wether Regal should have a notion of OPA versions, and perhaps do something like allow the use to set their current OPA version in the config, and have any rules that depend on a version greater than that automatically ignored (but perhaps with a warning)... 🤔

**Comment by srenatus** [comment]
How does regal know the version some rego code is supposed to run with? Btw, do we have capabilities support, so I could use regal on rego code that uses builtins that OPA doesn't know? 🤔 If we did use caps, we could introduce a "default_functions" feature, so that a caps file can be used to determined if the target OPA is able to eval default functions...

**Comment by anderseknert** [comment]
> allow the user to set their current OPA version in the config

So something like:

```yaml
rules:
  ...

opa:
  version: v0.52.0
```

No current support for capabilities, but should be fairly straightforward to add. We could even ship with a capabilities config that supported e.g. Gatekeeper, EOPA, and whatever else there is, out of the box. Having to bring that whole JSON file and edit it manually always felt somewhat "low-level" to me. We should look into some easier mechanics for Regal, like allowing capabilities to be defined in the Regal conf. I'll create an issue 👍
