### ISSUE TITLE
Dubious use of print + sprintf

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#220]
**Avoid**
```rego
allow {
    # if any of input.name or input.domain are undefined, this will just print <undefined>
    print(sprintf("name is: %s domain is: %s", [input.name, input.domain]))

    input.name == "admin"
}
```

**Prefer**
```rego
allow {
    # if any of input.name or input.domain are undefined, this will still print the whole
    # sentence, with the value undefined printed as such, e.g.
    # name is: admin domain is: <undefined>
    print("name is:", input.name, "domain is:", input.domain)

    input.name == "admin"
}
```
Since `print` allows any number of arguments, there's rarely any benefit to using `sprintf` for formatting. But more importantly, the `print` function is unique in that it will allow any arguments passed to be undefined without terminating, but will print such values as `<undefined>`. Using `sprintf` will however nullify this benefit, and just print `<undefined>` without the context.

It should be added to the notes on this that the use of `print` is discouraged outside of development, and other rules exists to check for its use. But in the context of development, one may of course choose to disable such rules, or have them ignored for e.g. `_test.rego` files... so I think having rules on how to make best use of `print` still makes sense.

**Comment by Ronnie-personal** [comment]
@anderseknert 
I'm getting started on this issue.

I run following commands to create the skeleton code in my local dev environment. 

`go build`   
`./regal new rule --category testing --name dubious-print-sprintf`

Two files are created under '.regal/rules/testing'.
dubious_print_sprintf.rego  dubious_print_sprintf_test.rego

Did I miss anything? The rego files are not be created under bundle directory.

**Comment by anderseknert** [comment]
That's great to hear! The `regal new rule` command assumes most people using it will do so for custom rules, so by default the `--type` is set to `custom`. Change this to `--type builtin` and the files should end up in the right location.
