### ISSUE TITLE
Metasyntactic variable

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#244]
https://en.wikipedia.org/wiki/Metasyntactic_variable

> Metasyntactic variables used commonly across all programming languages include [foobar](https://en.wikipedia.org/wiki/Foobar), foo, bar, baz, qux, quux, corge, grault, garply, waldo, fred, [plugh](https://en.wikipedia.org/wiki/Plugh), [xyzzy](https://en.wikipedia.org/wiki/Xyzzy_(computing)), and thud

This would be a good rule in the "testing" category (which is really more about "development" and should probably be renamed), as avoiding names like "foo" and "bar" seems like a reasonable thing to want in production policy.

**Comment by Parsifal-M** [comment]
Hey Team! 👋 

I wouldn't mind looking at this one, seems like a fun one!

Is there a similar rule I could use for inspiration? I've edited a rule before but not made a _new_ one so not sure what is required to fully implement this 😄 

Thanks!

**Comment by anderseknert** [comment]
Hey @Parsifal-M! Sorry, I didn't see this until now. I have actually been working on this in a branch, but not pushed it yet as I encountered some issues. If you'd like to work on something similar, perhaps this one would be a good candidate? https://github.com/StyraInc/regal/issues/220

To get started, you could run `regal new rule --category testing --name dubious-print-sprintf`.

This will create a generic policy and test in the `bundle/regal/rules/testing` directory, which you can use as a starting point. In order to understand what the AST looks like for this construct, you could create a file, say `p.rego` with an example:

```rego
package p

rule {
    print(sprintf("name is: %s domain is: %s", [input.name, input.domain]))
}
```

Then run `regal parse p.rego` to see the AST for the policy. This is what the input provided to the linter will look like. The tree for the rules would look something like:

```json
{
    "rules": [
      {
        "body": [
          {
            "index": 0,
            "location": {
              "col": 5,
              "file": "p.rego",
              "row": 4
            },
            "terms": [
              {
                "location": {
                  "col": 5,
                  "file": "p.rego",
                  "row": 4
                },
                "type": "ref",
                "value": [
                  {
                    "location": {
                      "col": 5,
                      "file": "p.rego",
                      "row": 4
                    },
                    "type": "var",
                    "value": "print"
                  }
                ]
              },
              {
                "location": {
                  "col": 11,
                  "file": "p.rego",
                  "row": 4
                },
                "type": "call",
                "value": [
                  {
                    "location": {
                      "col": 11,
                      "file": "p.rego",
                      "row": 4
                    },
                    "type": "ref",
                    "value": [
                      {
                        "location": {
                          "col": 11,
                          "file": "p.rego",
                          "row": 4
                        },
                        "type": "var",
                        "value": "sprintf"
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ],
        "head": {
          "location": {
            "col": 1,
            "file": "p.rego",
            "row": 3
          },
          "name": "rule",
          "ref": [
            {
              "type": "var",
              "value": "rule"
            }
          ],
          "value": {
            "type": "boolean",
            "value": true
          }
        },
        "location": {
          "col": 1,
          "file": "p.rego",
          "row": 3
        }
      }
    ]
  }
```
I removed some attributes for brevity, but what I think we'll need to look for (and likely in a `walk` iteration) is a terms array where the first item is a call to `print` and the next item is a "type": "call" and the ref a call to sprintf. It's a little hairy, but such is the ways of the AST :)

**Comment by Parsifal-M** [comment]
Sounds good to me! Will check it out, thanks @anderseknert!
