### ISSUE TITLE
Incorrect URL in Styra docs site for related resources

### ISSUE THREAD

**Issue by Parsifal-M** [StyraInc/regal#251]
Hey Team! 👋 

In the [Related Resources](https://docs.styra.com/regal/rules/style/detached-metadata#related-resources) on the Styra documentation site, the URL pointing to the OPA docs seems to be missing the `/docs/` part of the URL, so if you try to look at the resources it will `404`.

Examples:
- https://docs.styra.com/regal/rules/style/detached-metadata#related-resources
- https://docs.styra.com/regal/rules/style/opa-fmt

if you click on the related resources here to go and view the OPA documentation it will 404.

**Comment by anderseknert** [comment]
Thanks for reporting this @Parsifal-M 👍 There's a script somewhere copying files from this GitHub repo and converting them to Docosaurus docs for docs.styra.com. I believe the /docs/ part is intended to be cut from the GitHub links only and not links pointing anywhere else. 

@charlieegan3 could you PTAL when you have some time?

**Comment by charlieegan3** [comment]
Thanks for raising this, Regex is hard... 😬  I've got a fix open for this on our internal repo for the docs.

**Comment by Parsifal-M** [comment]
> Thanks for raising this, Regex is hard... 😬 I've got a fix open for this on our internal repo for the docs.

Saving the day! -> https://xkcd.com/208/

😆

**Comment by charlieegan3** [comment]
Ha, something like that! Or maybe rather the killer was Regex all along... 🤔

**Comment by anderseknert** [comment]
Thanks for the fix @charlieegan3 🥳
