### ISSUE TITLE
Update Development docs to remove build.sh reference

### ISSUE THREAD

**Issue by mcguiresm** [StyraInc/regal#261]
Currently the [Development doc](https://github.com/mcguiresm/regal/blob/main/docs/development.md) still references the `build.sh` script that was removed in #247. Needs to be updated to reflect calling the `fetch_builtin_data.sh` from inside the `build` directory.

**Comment by anderseknert** [comment]
Thanks @mcguiresm! Would you want to submit a fix?

**Comment by mcguiresm** [comment]
😃 already working on it
