### ISSUE TITLE
Files ignored may still cause parse errors

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#265]
This came up when testing Regal against a repo where a few files were used as templates, i.e. something like:
```
package {{org_name}}.authz

# ...
```
Now this is obviously not a valid Rego file, and should be ignored for evaluation. But since we do the ignore check *after* we've parsed the files, this fails even when ignoring the directory or these files.

Doing the ignore check in Rego is likely the best option for rule level ignores, as you won't want to ignore a parse error only for a certain rule, but perhaps we'd need to make the global ignore check in Go before the files are parsed.

Alternatively, we could still leverage the check in Rego, but have Regal do something like:

- Gather all files lined up for evaluation.
- Pass the list for evaluation using the config policy, which...
- Returns the list with any files and directories that should be ignored removed.

This options would be more arduous, but it would benefit from having the same ignore logic for both global ignore directives as well as for rule level ignores.

**Comment by anderseknert** [comment]
We even have this type of files in our [repo](https://github.com/StyraInc/regal/tree/main/internal/embeds/templates) 😄
Using `.rego.tpl` or something like that is a good way to avoid this problem, but we can't necessarily force that convention in other repos.

**Comment by anderseknert** [comment]
Ah, right, we have the ignore logic implemented both in Go (for Go rules) and in Rego for Rego rules. The quick fix would be to leverage the Go ignore logic then, and perhaps look into something more elaborate for later. I'll go with that.

**Comment by kristiansvalland** [comment]
Hmm, I see.
As you are onto, I suppose a future alternative could be to move the go logic back into Rego and then use OPA to evaluate that based on some input structure before the actual linting -- To avoid duplication of code. The reason I did not do this at the time was to keep the PR appropriately small.

Probably requires some refactoring of the Rego rule for ignore directive and how we tie into OPA evaluation from Go.

**Comment by anderseknert** [comment]
Yep, and you made the right call 👍 I'll working on a fix for the immediate issue to have it working with the next release, but I can create another issue for consolidating the ignore logic in Rego later.
