### ISSUE TITLE
Prefer set/map generating rule over comprehension in head

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#370]
Yet another rule in the style category, but I guess that's just the nature of this thing 😅 The idiomatic category could be considered too, but it's all rather arbitrary anyway.

Clearly, the name needs some further thought as well, _but_:

**Avoid**
```rego
package policy

import future.keywords

employee_emails := {email |
    some email in input.emails
    endswith(email, "@acmecorp.com")
}
```

**Prefer**
```rego
package policy

import future.keywords

employee_emails contains email if {
    some email in input.emails
    endswith(email, "@acmecorp.com")
}
```

**Rationale**
1. Reads much better / more descriptive
2. The partial rule can easily be extended by adding more rules
3. The partial rule can easily be extended by adding variables (general refs)

**Exceptions**
1. Array comprehensions
2. Simple conversions, like `my_set := {x | some x in arr}`
3. Comprehension in head, where there's an actual rule body
4. Comprehensions anywhere else

**Comment by Parsifal-M** [comment]
I like it, and agree it reads much better 👍

**Comment by charlieegan3** [comment]
I think this makes sense yeah. It's a style one but a good reminder to people that set comprehensions also work (better) as a 'contains rule'.

> The partial rule can easily be extended by adding more rules

I think this is the top reason in the Rationale as it's unsubjective.

**Comment by anderseknert** [comment]
Indeed! It was not meant as an ordered list, but you're right :)
