### ISSUE TITLE
Validate that the rules supplied to Regal conform to some basic requirements

### ISSUE THREAD

**Issue by charlieegan3** [StyraInc/regal#38]
All rules supplied to Regal should have the following set:

* title
* description
* custom.category

x-ref: https://github.com/StyraInc/regal/pull/37#discussion_r1123048052

**Comment by anderseknert** [comment]
Category and title is now enforced by the package path. Description is now set in a package level annotation, and while it's not enforced I don't believe it's easy to miss, and all sorts of tests are going to fail without it anyway. 

I think we can close this, and if there are other validations we can make for rules or custom rules, let's create issues for those as we find out about them.
