### ISSUE TITLE
opa-fmt rule description to include --write

### ISSUE THREAD

**Issue by Parsifal-M** [StyraInc/regal#381]
Hey Team! :wave: 

Bit of a silly one maybe, I was thinking would this not be better for the description for the opa-fmt rule?

```bash
Description:  	File should be formatted with `opa fmt --write`
```

A few times I've just gone "Oh yeah, opa-fmt" and it just prints to stdout then I remember why :sweat_smile: 

Again, could just be me being absent-minded :laughing:

**Comment by anderseknert** [comment]
That's good feedback! I've also forgotten to add that flag at times, although seeing the file printed to the console immediately reminds me about what I did wrong. I could totally see how someone not experienced with the command would have a hard time coming to the same conclusion. Checking the [documeentation for that rule](https://docs.styra.com/regal/rules/style/opa-fmt), it does say:

> A good idea could be to run opa fmt --write on save, which can be configured in most editors.

But perhaps that sounds like it's only related to editor settings. The section before that reads:

> The opa fmt tool ensures consistent formatting across teams and projects. Unified formatting is a big win, and saves a lot of time in code reviews arguing over details around style.

We could add another sentence to that parapgraph saying something like:

> Use `opa fmt --write` on any file before commiting a change.

I'm hesitant to update the description of the rule though, as ultimately the "Regal experience" requires reading the docs of any rule. We don't want users to blindly "fix" issues, but to learn about why Regal considers something to be an issue in the first place, and to make an informed decision if they want to include that rule in their project(s).

If you'd like to update the docs on that rule like suggested (or something similar), that'd be a welcome PR :)

**Comment by Parsifal-M** [comment]
Hey! 👋 

> I'm hesitant to update the description of the rule though, as ultimately the "Regal experience" requires reading the docs of any rule. We don't want users to blindly "fix" issues, but to learn about why Regal considers something to be an issue in the first place, and to make an informed decision if they want to include that rule in their project(s).

I had not considered this, and it makes a lot of sense when you put it that way.

> If you'd like to update the docs on that rule like suggested (or something similar), that'd be a welcome PR :)

Sure I can look into this 👍

**Comment by anderseknert** [comment]
If you want to update the docs on this, feel free to submit a PR @Parsifal-M 👍 
Closing this issue though as we agree on leaving the `description` field as is.
