### ISSUE TITLE
use-assignment-operator does not detect else-clauses declared using unification

### ISSUE THREAD

**Issue by ThomasKingoTM** [StyraInc/regal#385]
**The "use-assignment-operator" does not detect else-cases like the following:** 

decision := {...} {
} **else =** {...} {}

The linter rule should suggest this instead:
decision := {...} {
} **else :=** {...} {}

I've parsed both and their ASTs are identical - as the unification operator is simply parsed into an assignment.

**Comment by anderseknert** [comment]
Thanks for reporting this! We do leverage some tricks to detect this in other places, and I'm hoping we can do so for `else` too. I'll take a look.

**Comment by srenatus** [comment]
> I've parsed both and their ASTs are identical - as the unification operator is simply parsed into an assignment.

This is correct, it's mostly a matter of a consistent language surface. It won't behave any differently if it's using `:=` over `=`.
