### ISSUE TITLE
Function without args

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#396]
**Avoid**
```rego
f() := true if condition
```

**Prefer**
```rego
f := true if condition
```

**Comment by anderseknert** [comment]
This is already corrected by `opa fmt`, but the more policy I see not formatted using that tool, the more convinced I'm starting to get that we'll need to accept some overlap.

**Comment by srenatus** [comment]
arity-0 functions are problematic and most likely a mistake. Are they included in the full extent, btw? [yes they are](https://play.openpolicyagent.org/p/Ex8eGVkR9Q) so they really are not proper functions...

**Comment by anderseknert** [comment]
Yes, also, seems to have some rather odd behavior I'm not sure I understand.

https://play.openpolicyagent.org/p/zvPotrbett

Change `input.message` on line 9 to "foo" and try eval.

**Comment by srenatus** [comment]
What...? 😮
