### ISSUE TITLE
Prefer function arg pattern matching for equals condition

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#397]
Few know about this capability, so it'd be great if Regal would educate its users on this!

**Avoid** (is a strong word here, but...)
```rego
package policy

is_one(number) := number == 1

bool_to_string(bool) := "true" if bool == true
bool_to_string(bool) := "false" if bool == false
```

**Prefer**
```rego
package policy

is_one(1)

bool_to_string(true) := "true"
bool_to_string(false) := "false"
```

**Comment by srenatus** [comment]
[Totally!](https://github.com/StyraInc/regal/blob/main/bundle/regal/ast.rego#L195-L208) :+1:

**Comment by anderseknert** [comment]
Heh, yeah, we might need to use a few `# regal ignore: ...` for this in Regal.
Pattern matching was IIRC significantly slower _when done a million times_ compared to equals in the body. Not sure if that's a detail worth mentioning in the docs for this. Could obviously have been an error measuring from yours truly, but I remember running those tests several times. May need to revisit, and if it's still so, might be worth creating an issue for that in OPA.

**Comment by anderseknert** [comment]
@srenatus ah, there was that note: https://github.com/anderseknert/rego-perf-tuning#observations

**Comment by anderseknert** [comment]
FWIW, I have code written to solve this for at least the simple cases, as provided in the examples above. However, learning that `opa fmt` rewrites `f(1)` -> `f(1) = true` feels like a dealbreaker here, as we also encourage formatting using the OPA formatter :/ 

Lobbying to get the shorter format recognized by the formatter, while perhaps still respecting the longer format if the user provided it so. We'll see where that ends up, but until then, I'm blocked on this.
