### ISSUE TITLE
Add documentation page for CI integration

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#405]
We currently provide an intro to using the GitHub Action here: https://github.com/StyraInc/regal#github-actions

I think it would be good to break that out into a separate page on the topic of CICD integration, where we could include GitLab, and possibly other build systems.

**Comment by Parsifal-M** [comment]
Hey! :wave: 

I will add some docs for using regal in Gitlab using the container image :+1: 

I could also add maybe some instructions by downloading the binary but I think the docker image will be the way forward for most :sweat_smile: 

Will pick this up tomorrow/friday :heart:

**Comment by anderseknert** [comment]
That's awesome @Parsifal-M 👍 Just create a new doc in the docs directory called `cicd.md` or something like that, and remember to add a link or two from the README :)

For GitHub, you could just copy some of the content from https://github.com/StyraInc/setup-regal
