### ISSUE TITLE
AST location usage improvements

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#408]
Wading through tons of AST JSON this evening and... TFW I realized that despite having read probably hundreds of thousands of lines of AST JSON by now, it never struck me before how the `"file"` attribute of *all* `location` attributes are identical across an entire module. In some AST modules, I'm counting _13K places_ where we have something like `{"file": "policy.rego", ...}`. 

Obviously, this is a waste of everybody's time, and we should look into having that attribute removed. I think we'll need to do this in OPA similarly to how we included the `text` attribute recently. One question of interest would be what motivates this in OPA in the first place? At least when scanning a full module, it seems like it would be enough to place this only on the package location.

While we're looking into this, it'd be interesting to see if there are any `location` attributes that we never make use of in Regal. I do think we use most of them, but if we can drop a few, there'll be less nodes to walk.

**Comment by anderseknert** [comment]
Ping @charlieegan3, since this is clearly your turf :)

**Comment by charlieegan3** [comment]
> One question of interest would be what motivates this in OPA in the first place? At least when scanning a full module, it seems like it would be enough to place this only on the package location.

I suppose it makes the JSON very verbose, especially so when pretty printed. I guess the one benefit I can see is that you have all the information you need when inspecting a particular AST node, rather than needing to do some file lookup based on the package.

> if there are any location attributes that we never make use of 

So I guess we use row and col all the time. File less so, but still required, and we recently added support for `IncludeLocationText` too. I don't think there are any others, but we use them all right?

**Comment by anderseknert** [comment]
> I suppose it makes the JSON very verbose, especially so when pretty printed

Indeed, and worse, it'll have the `walk` function traverse a lot of extraneous elements.

>  I guess the one benefit I can see is that you have all the information you need when inspecting a particular AST node, rather than needing to do some file lookup based on the package.

Yeah, I'm just wondering if there's ever an actual case where you're working with AST nodes without having that context.

As for what we use and don't use, I'd be curious to know if there are any locations we never check... it doesn't sound trivial to find out though, so perhaps we can leave that be for the time being.

Would removing the `file` attribute from the location require something similar to `IncludeLocationText`? 
So we'd have something like `IncludeLocationFile` and set it to `false` for our purposes?

**Comment by charlieegan3** [comment]
> IncludeLocationFile 

Yeah, that's one option we have. Seems like a pretty good one. It's be nice to motivate it by knowing how much time this saves us on a large parse.

Could we grep out the location using [Gron](https://github.com/tomnomnom/gron) or similar and see what the performance benefit is?

**Comment by anderseknert** [comment]
Yes, we could probably have some temporary code too that just walks the *ast.Module and nils them all out before we send the AST in for evaluation, then just measure the difference in eval time.

Motivation should however also include having to read this in the AST we work with all the time, as well as having to include it in all of our unit tests, and so on :)

**Comment by anderseknert** [comment]
On the topic of redundant data, or at least so for our purposes — each element in the body array contains an `index` attribute, which is just... well, the index of the array item. I suppose this could be useful in some cases, but we don't currently need it. It's however nowehere near as frequent as `file`, so I don't think it's worth spending any effort to have that removed.

**Comment by anderseknert** [comment]
Fixed in https://github.com/StyraInc/regal/pull/458

The "index" attribute of rule bodies is a non-issue, so let's drop that.
