### ISSUE TITLE
regal/linter in playground not active?

### ISSUE THREAD

**Issue by hpvd** [StyraInc/regal#421]
just give https://play.openpolicyagent.org/ a test

-> no matter what I try, the linter always says "No linter violations"
--> when does it check?

maybe we could/should add a "broken" example with linter output?

if relevant: used chrome and FF

**Comment by hpvd** [comment]
ok, the problem was in front of the screen...
was pretty sure it is also checking the structure of the input data...
having the linter result window on the right side below the input data has strengthened me in this misconception

learnings:
- me: do not try new things after a too long day
- regal: maybe one should position the linter window below the rego rule window
- regal: maybe one can also check the input data (possibly with a standard json linter, or if there are also advanced ideas regarding structure of input data (->speed?) maybe one can think further on this)

**Comment by hpvd** [comment]
closing...

**Comment by anderseknert** [comment]
Appreciate the report either way, @hpvd 👍  Would love it if you'd join us in the **#regal** channel in the [Styra community Slack](https://communityinviter.com/apps/styracommunity/signup).

**Comment by hpvd** [comment]
many thanks for the kind words and pointing to schema functionality of rego for this!

just working with this in a slightly other field and use cue.
Since there are some parallels between rego and cue,
I'd like to use the chance to point to theses resources, since there maybe some really interesting inspiration in it:
(sorry for off-topic, think of passing it to https://github.com/open-policy-agent/opa)

1) great overview:
https://www.youtube.com/watch?v=m6g0aWggdUQ&t=740s
![2023-10-26_09h22_47](https://github.com/StyraInc/regal/assets/5681880/011e063b-fd1e-4ff5-af38-cbb5c7e67592)



2) Rego and Cue: comparison, learning and possible interaction:
https://github.com/cue-lang/cue/discussions/818

3) offical:
https://cuelang.org/
