### ISSUE TITLE
Rule: `unnecessary-some` when some is not used for iteration

### ISSUE THREAD

**Issue by kristiansvalland** [StyraInc/regal#440]
## Description

In my opinion, the following

```rego
some "a" in ["a", "b"]
```

is allowed, but looks weird and would be better written as

```rego
"a" in ["a", "b"]
```

I.e. the `some` keyword is in this case unnecessary, giving the name to this rule.

I first thought that this was a bug in the OPA syntax and I considered adding an issue there, but then I discovered the types given in the "Potential pitfalls" section that are kind of similar but are correct.

## Testing

I tested the following policy with Regal v0.11.0, and no complaints from existing lints were given

```rego
package play

import future.keywords.if
import future.keywords.in

a if {
        some "a" in ["a", "b"]
}
```

## Potential pitfalls

The following should not be flagged by the lint rule

```rego
some idx, "a" in ["a", "b"]
```

**Comment by anderseknert** [comment]
Thanks @kristiansvalland! Yeah, I could definitely see how someone new to Rego would make that mistake, and we should flag it even if harmless 👍
