### ISSUE TITLE
Lint with `--profile` showing suspiciously low `num_eval` count

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#457]
Linting Regal's own `bundle` directory, which contains 118 Rego files, 
```json
{
  "location": "/regal/rules/style/line_length.rego:18",
  "total_time_ns": 748651746,
  "num_eval": 364,
  "num_redo": 182,
  "num_gen_expr": 4
},
```

Line 18 is the last line in this snippet:
```rego
some i, line in input.regal.file.lines

line_length := count(line)
line_length > cfg["max-line-length"]
```

OK, so number crunching isn't our strong side, but...

Cloc tells us we have 5638 lines of _code_, and of course even more counting whitespace
```
$ cloc bundle
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Rego                           118           1461            516           5637
```

As each line of each file is evaluated, I'd expect the `num_eval` number to be somewhere close to that, but instead we have `364`. Perhaps I need to be educated in how that works, or perhaps there's an issue in how we collect and report that.

**Comment by srenatus** [comment]
If I had to guess, the profile is perhaps overwritten for each lint run...? So you captured the last run only... 🤔

**Comment by anderseknert** [comment]
Yeah, that’s my guess too. Will need to dig in 🤓

**Comment by srenatus** [comment]
There's some [profile aggregation logic over here](https://github.com/open-policy-agent/opa/blob/f6b54ccad9ac86f0c83b163bb3bb2d465bd61a0a/profiler/profiler.go#L309), perhaps it could come in handy.
