### ISSUE TITLE
False positive in `unnecessary-some`

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#459]
Not sure what's going on here, but the new `unnecessary-some` rule is flagging this policy, which I've reduced from one in the [ScubaGear](https://github.com/cisagov/ScubaGear/) code.
```rego
package p

import future.keywords.in

types := []

conditions := ["t" in types]
```

**Comment by srenatus** [comment]
This is the policy when the compiler is done with it:

```rego
package p

types := [] { true }
conditions := [__local0__] {
    true
    __local1__ = data.p.types
    internal.member_2("t", __local1__, __local0__)
}
```
I guess it looks suspiciously like `some "t" in types`? 🤔

**Comment by anderseknert** [comment]
Yeah, it does. I’d love to look into it now, but being forced up at 4:50 AM this morning is starting to take its toll 😩😅

**Comment by srenatus** [comment]
I've been silly, too, the parser output matters here, not the end product of the compiler stages. But it'll look similar, I suppose.

**Comment by anderseknert** [comment]
The culprit was not checking for `symbols` in the rule.
