### ISSUE TITLE
Rule: `boolean-assignment`

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#465]
**Avoid**
```rego
is_snake_case(str) := str == lower(str)
```

**Prefer**
```rego
is_snake_case(str) if str == lower(str)
```

Controversial, perhaps? 😅 Just finding a few of these myself in Regal's codebase, and I'd like to be made aware of them, as the assignment is almost always redundant, and leaning in on undefined should be considered idiomatic.

The rule could also check for assignment _from_ boolean functions:

```rego
allow if {
	sw := startswith("f", "a")
	# ...
}
```
But perhaps that should be a different rule? 🤔

**Comment by anderseknert** [comment]
@srenatus @charlieegan3 WDYT?

**Comment by srenatus** [comment]
> Controversial, perhaps? 

Yeah, a bit. It think this is a style preference... so I guess if teams can come to the agreement that they'd like a consistent style, it would make sense to have a rule. But since it's stylistic, I could even see Avoid/Prefer swapped if that's your choice 🙃 🔀

**Comment by anderseknert** [comment]
> Yeah, a bit. It think this is a style preference

To some degree, yes, but I think the difference to me is "do you understand undefined or not", and passing around boolean values would indicate that maybe you don't, which is why I was leaning towards this being in the idiomatic category. But it's not a hill I'll die on :)

**Comment by anderseknert** [comment]
It seems like my ideas aren't getting traction, but I'm a merciful ruler, so I'll update the category to style.

**Comment by anderseknert** [comment]
Got code for this now and ran it against 10 popular policy repos. Very few violations, and max 3 in any given repo. So I'm back to saying this is idiomatic.
