### ISSUE TITLE
`unused-return-value` false positive when used with `print`

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#474]
```rego
package p

r {
    print(lower("A"))
}
```

The above triggers the `unused-return-value` rule for the `lower` function, which is of course not correct. Nesting other functions seems to work as expected, so this is likely due to an exception being made for the print call itself.. not sure.

**Comment by srenatus** [comment]
Interesting. Would it also flag
```rego
package p
r {
  count({ __local__ | lower("A", __local__)}
}
```
this would be -- I think -- what the compiler does with the print calls, except that we end up calling `count` instead of `internal.print`

**Comment by anderseknert** [comment]
Remember that we're only working at the level of the AST here though :) But yeah, I'd expect that to be flagged, or if not it would be a `function-arg-return` violation post rewrite.

**Comment by srenatus** [comment]
🤦 I keep forgetting that the compiler has nothing to do with it...thanks for the reminder.
