### ISSUE TITLE
Allow custom rules to be provided with raw contents / via an `fs.FS`

### ISSUE THREAD

**Issue by jamietanna** [StyraInc/regal#492]
When using the Go API for regal, it's possible to set custom rules [by path](https://pkg.go.dev/github.com/styrainc/regal@v0.13.0/pkg/linter#Linter.WithCustomRules).

However, this only works when the files are available on disk.

For instance, if you wanted to wrap regal as part of a separate binary, we'd want to package up the files in the binary with [an `embed.FS`](https://pkg.go.dev/embed#hdr-Directives).

When an `embed.FS` is used, we'd need to unwrap the directory and copy it to the local file system to use.

It'd be convenient if we could either:

- Provide a map of filename-to-contents 
- Provide an `fs.FS` (which satisfies `embed.FS`) 

This would allow more flexibility for different use-cases.

**Comment by anderseknert** [comment]
Agreed, that sounds like a good addition.
