### ISSUE TITLE
Use matrix for building on linux, mac, windows

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#494]
We used to do this for Linux + Windows in the past, but rq was broken on Windows, so we moved that out into a separate job where we don't use rq. @charlesdaniels have fixed the Windows issue now, so we should go back to have a single job building using a matrix for all three operating systems.

(We don't currently build for Mac, but there's no reason not to add that too)

**Comment by charlieegan3** [comment]
Fixed in #495
