### ISSUE TITLE
SARIF: `region` should be omitted if result refers to the entire artifact

### ISSUE THREAD

**Issue by travbale** [StyraInc/regal#514]
Rules like `opa-fmt` that refer to the entire file (known as an artifact in SARIF) should omit the region block per guidance in [§3.29.4](https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/sarif-v2.1.0-errata01-os-complete.html#_Toc141790932). 

Currently for rules that apply to the entire artifact the region block is set to the following:

```json
{
    "region" :{
        "startLine": 0,
        "endLine": 0
    }
}
```

This ends up violating the [JSON Schema](https://github.com/oasis-tcs/sarif-spec/blob/main/Schemata/sarif-schema-2.1.0.json#L1713-L1723) which requires a minimum value of 1 for both `startLine` and `startColumn`.

**Comment by anderseknert** [comment]
Thanks! That should be an easy fix. I'll take a look.
