### ISSUE TITLE
Enhancement: Regal appears to be using Node 16 

### ISSUE THREAD

**Issue by crutchfield** [StyraInc/regal#559]
Node 16 has reached its [end of life](https://github.com/nodejs/Release/#end-of-life-releases),

Receiving the following annotation when running action: 

[Run-OPA-Tests](https://github.com/xxxx/yyyyyyy/actions/runs/7931518495/job/21655936050)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: StyraInc/setup-regal@v0.2.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by srenatus** [comment]
https://github.com/StyraInc/setup-regal/tree/v1 v1 should be using a newer version as of earlier this week

**Comment by crutchfield** [comment]
> https://github.com/StyraInc/setup-regal/tree/v1 v1 should be using a newer version as of earlier this week

Thanks for the quick response.  We will step up to the latest ASAP.
