### ISSUE TITLE
Clarify the `[rule].ignore .files` option in the documentation 

### ISSUE THREAD

**Issue by bdumpp** [StyraInc/regal#561]
It is not clear from the documentation that the you can add [rule].ignore.files to ignore files for a specifc rule. It is only clear that you can ignore all rules for specific files and that you can ignore files in opa-fmt. https://docs.styra.com/regal#configuration

**Comment by anderseknert** [comment]
Thanks for reporting that @bdumpp 👍 I'll make an update to the docs to make that more clear.
