### ISSUE TITLE
Invalid code and severity values in LSP server's response

### ISSUE THREAD

**Issue by folliehiyuki** [StyraInc/regal#585]
* In a valid document, the server responds with `code` field being a JSON object containing `value` and `target` keys. The official LSP specs only allows int or string.
* In an invalid document, the server responds with `severity = 0` (default empty int value, I suppose), which is not in the allowed range [1, 4]. The diagnostic message is still displayed fine though.

Ref: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnostic

More details can be seen in the [original comment](https://github.com/StyraInc/regal/issues/578#issuecomment-1973783653).

**Comment by charlieegan3** [comment]
Thanks for opening a new issue for this @folliehiyuki, I'll take a look at this on Tuesday. Have a great weekend.

**Comment by charlieegan3** [comment]
Hi @folliehiyuki, sorry for the radio silence last week. I have had a go at some fixes in https://github.com/StyraInc/regal/pull/594. It seems to work ok in VS Code ok, would you be able to do some testing with a build from this branch to check is works for you use case too?

**Comment by folliehiyuki** [comment]
I don't have access to my development computer now, so let me report back this weekend.

Thanks for working on it!
