### ISSUE TITLE
Allow setting log level for LSP output

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#615]
With the amount of events logged by the language server, good ol' `print` call debugging is made tedious as you'll have to scroll by / search a huge number of messages in order to find what you're looking for. It would be nice if it was possible to set a log level, or otherwise mute any log events not interesting for the time being, and only have the relevant events displayed in the output.

**Comment by charlieegan3** [comment]
I was thinking about this too. It's made trickier that stdout is used for the messages, and stderr must be used for any extra messages. I was considering some kind of debug server that allowed you to inspect the different parts of the cache and to show the latest log messages too. I think this would be quite simple to add and would just listen on another port.

Perhaps over engineering, but I was always wanting to check the different parts of the server state while it was running.

**Comment by anderseknert** [comment]
Yeah, that'd be useful! Although to solve the immediate problem, I'm most often just interested in a single type of event, so if I could have all the logs on e.g. "info" level muted, and set the one I care about to "error", that would probably be good enough for me.

**Comment by charlieegan3** [comment]
https://github.com/StyraInc/regal/pull/623 would be part of the solution, but I guess the main thing would be making this an option that could be set from the LSP client too. Or perhaps it should just come from Regal's config file?

**Comment by anderseknert** [comment]
I'll try this out when I have time, but I think this will almost be good enough. The only thing I would need now is a method that would log regardless of verbose being set, as that would make it easy to see whatever I'm interested in. And that is of course trivial to add when debugging... so I think we can close this.

**Comment by charlieegan3** [comment]
We can make it better, but l.logError will do that. Verbose logging is just a toggle for the request logs at the moment.
