### ISSUE TITLE
Possible to specify path to Regal config file in the OPA VSCode Extention

### ISSUE THREAD

**Issue by bdjgs** [StyraInc/regal#626]
A setting for the OPA VSCode Extention that allows to specify a path to a Regal config file. 

Currently, it is required to have a .regal/config.yaml at the root of the every project. It would be great to be able to specify a path to a global Regal config that is used in all projects, if a local is not present.

**Comment by charlieegan3** [comment]
Hmm, good point. Regal itself is actually designed with this in mind (see here: https://docs.styra.com/regal#configuration). However, this functionality isn't the same when Regal is running as a language server.

Let's fix that! 

One thing I'm not sure about is what to do when the global config changes while the server is running. At the moment, the client sends information about the updated config file to the server and it updates. However, then the config file loaded is outside the workspace of client, then we won't get updates in the same way. I think we'd need to implement some fsnotify based watching of the higher level config file. Doable, but less simple.

I guess the other option is that we allow the user to set a global config in the VSCode config, however, I like this less as it deviates from the Regal CLI behaviour, and still needs to the fsnotified...

**Comment by anderseknert** [comment]
Thank you both!

@bdjgs may correct me if I'm wrong, but I would not expect a global Regal configuration shared between many projects to see that frequent updates. Considering the intricacies of fsnotify and portability, perhaps it'd be fine considering config outside of the workspace as static? At least for a first implementation. 

> I guess the other option is that we allow the user to set a global config in the VSCode config, however, I like this less as it deviates from the Regal CLI behaviour

Wouldn't that be equivalent to point out a config file via the CLI's `--config-file`?

**Comment by bdjgs** [comment]
I dont know much about VSCode extentions so maybe the following is not possible, but I think it would be fine if the configfile is only loaded when a new workspace is loaded in VSCode. I do also think that it would be static for the most time and then when a change needs to be made, the user just have to reopen the VSCode workspace to reload the configfile. 

The feature request comes from the fact that if there is a central team managing the Regal configuration for a bunch of teams. If each team want to use this Regal linting locally, they would need to have the configfile, so they dont get errors on stuff that is ignored by the central team. And instead of each team having to have a configfile in each of their Rego projects, they can just have a global configfile on their PC and then update it whenever the central team annonces that changes has been made.

**Comment by anderseknert** [comment]
Yep, certainly a valid scenario. I wonder if the VS Code client deals gracefully with symlinks?

I mean, if it does, I guess you could have `.regal/config.yaml` in your gitignore and linked to `~/org/.regal/config.yaml` or something like that?

**Comment by bdjgs** [comment]
Good idea, but it didn't work for me. The file correctly changed when changing the global config, but VSCode didn't seem to detect it. However, if I close the workspace and reopen it again, it works. 

I think this could be a viable solution, where I just have to reopen the workspace when changing the global config. 

I will let you guys decide if the symlink should be the solution or if you think the extention should be able to support a global Regal config.

**Comment by anderseknert** [comment]
I think we should support it the same way the CLI takes a `--config-file`. But since symlinking works but without tracking updates, I guess it would be pointless to implement this without fsnotify watches like @charlieegan3 suggested.

**Comment by charlieegan3** [comment]
Hey @bdjgs, we've just merged a related change for this in #650. Would you be able to confirm that this works for your use case? A simple `go build` should get you a binary but I can provide one if need be.

This change has the language server search in dirs above the current workspace to find a config file. You asked for a means of setting the config file explicitly, so just keen to check if this works. If not, we'll need to have a think about how best to offer that.

**Comment by anderseknert** [comment]
We save the binaries from any CI build nowadays, so you could find them [here](https://github.com/StyraInc/regal/actions/runs/8689132600#artifacts) from you latest `main` build :)

**Comment by bdjgs** [comment]
When opening a workspace it does succesfully find ./regal/config.yaml file in a parent directory, so that works great and removes the need for the symlink 👍

However, the plugin does not respond to updates in the config, dont know if that was desired or not. Responding to updates in global config requires a reload of the workspace. 

In my opinion I think that is okay because the config will not get updated that often. It is not a big deal for developers to reload their policy workspace on the few occasions that the global config changes. Developers do probably close the policy workspaces each time they are finished working on the policy anyways. And then if an update to the global config has been made, it will get loaded next time they have to work on their policy.

**Comment by anderseknert** [comment]
No, that sounds like an issue, as there's a filewatcher set up to monitor changes. We'll take a look! Good to know that scanning parent dirs is enough to resolve the issue though, once file updates are handled properly.

**Comment by charlieegan3** [comment]
Hmm, interesting. There is a video of it working on my machine in here in the PR body: https://github.com/StyraInc/regal/pull/650#issue-2238226071

Can you share how you're updating the config file in the parent dir and what operating system you're on as this sounds like a bug.

**Comment by anderseknert** [comment]
I just tested it and it works on my machine too... even did the config file edit in nano so that VS code wouldn't know about it, lol

**Comment by bdjgs** [comment]
ohh, let me test again :)

**Comment by bdjgs** [comment]
It might be because I am using WSL. I will record a video tomorrow (including the extention settings) and also try and set it up on Windows (the CI build does however not seem to produce Windows binaries).

**Comment by anderseknert** [comment]
Yeah, some issues with producing windows binaries in that workflow, as described here: https://github.com/StyraInc/regal/pull/610

You could always check out the repo and `go build` though.

**Comment by charlieegan3** [comment]
WSL ok cool, thanks that's good to know. I wonder if we can use a polling system in such cases.

Perhaps regal's watcher implementation could even determine if the system is working for fsnotify and choose to enable polling based on that.

**Comment by bdjgs** [comment]
Since it is working on your systems, I think we can go ahead and close the issue. WSL users can probably live without the support for live update of the config file. 

Having trouble building with Go on Windows due to corporate PC. So I will wait a bit until next release and test it on Windows.

**Comment by anderseknert** [comment]
Thanks for the update! Will close for now then, but if it doesn't work on "normal" Windows, we'll re-open.

**Comment by bdjgs** [comment]
Both me and one of my colleagues have not been able to get this to work on Windows. 

I have the following folder structure:

```
git
├── .regal
│   └── config.yaml
└── project1
    ├── README.md
    └── policy
        └── api
            └── authz
                └── authz.rego
```

Then I have a VSCode window opened at the git folder and one open at the project1 folder.

Unfortunately we do not have any screen recoding software on this corporate PC, so I can only screen record in a way that generates a file over the 10MB which is the file limit on Github. I have sent you a video on Slack.
