### ISSUE TITLE
Installing OPA - extension server exited

### ISSUE THREAD

**Issue by scoop96** [StyraInc/regal#682]
Hi, we are starting to test OPA-Rego at work, and i found in the repo a similar closed issue with regal two weeks ago.
OS is a windows 10.

When I add the opa VSCODE extension it installs regal and opa, i added them to the path (both account and system environmental variables)

here is the VSCODE Output from regal

```
panic: runtime error: index out of range [0] with length 0

goroutine 19 [running]:
github.com/styrainc/regal/pkg/config.FindRegalDirectory({0xc0002b47c1, 0x1d})
	/home/runner/work/regal/regal/pkg/config/config.go:138 +0x465
github.com/styrainc/regal/pkg/config.FindConfig({0xc0002b47c1?, 0xc0002d81e0?})
	/home/runner/work/regal/regal/pkg/config/config.go:147 +0x1c
github.com/styrainc/regal/internal/lsp.(*LanguageServer).handleInitialize(0xc000096880, {0x140?, 0x15b2220?}, 0xc0002b21e0?, 0xc0002b0ba0)
	/home/runner/work/regal/regal/internal/lsp/server.go:1024 +0x517
github.com/styrainc/regal/internal/lsp.(*LanguageServer).Handle(0xc000096880, {0x1b7f1e8, 0xc0000afc20}, 0xc00008ca20, 0xc0002b0ba0)
	/home/runner/work/regal/regal/internal/lsp/server.go:102 +0x191
github.com/sourcegraph/jsonrpc2.(*HandlerWithErrorConfigurer).Handle(0xc00008aeb0, {0x1b7f1e8, 0xc0000afc20}, 0xc00008ca20, 0xc0002b0ba0)
	/home/runner/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.2.0/handler_with_error.go:21 +0x57
github.com/sourcegraph/jsonrpc2.(*Conn).readMessages(0xc00008ca20, {0x1b7f1e8, 0xc0000afc20})
	/home/runner/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.2.0/conn.go:205 +0x2dd
created by github.com/sourcegraph/jsonrpc2.NewConn in goroutine 1
	/home/runner/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.2.0/conn.go:62 +0x1e6
[Error - 10:05:40 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:05:40 AM] Connection to server got closed. Server will not be restarted.
[Error - 10:05:40 AM] Regal LSP client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:05:40 AM] Server process exited with code 2.
```

Here is the VSCODE settings.json from the extensions

```
    "opa.dependency_paths.opa": "C:\\Users\\SE99236\\opa.exe",
    "opa.dependency_paths.regal": "C:\\Users\\SE99236\\regal.exe",
    "opa.languageServers": [
        "regal"
    ]
```

**Comment by anderseknert** [comment]
Hi there @scoop96! And thanks for filing an issue, although I obviously wish you didn't have to 🙂

The trace you provided (thanks for that too!) suggests the issue is encountered when Regal traverses your directory tree looking for a config file:

```go
// Move up one level in the directory tree
parts := strings.Split(dir, rio.PathSeparator)
parts = parts[:len(parts)-1] // <-- referencing index 0 in an empty slice here which causes the panic
```

I'm not sure why this would happen, but at least it's obvious where it happens. The docs for `strings.Split` says:

> Split slices s into all substrings separated by sep and returns a slice of the substrings between those separators.

> If s does not contain sep and sep is not empty, Split returns a slice of length 1 whose only element is s.

> If sep is empty, Split splits after each UTF-8 sequence. **If both s and sep are empty, Split returns an empty slice.**

The second argument here comes from `os.PathSeparator` and that should never be empty. It's not documented above, but it seems like `strings.Split("", "\\")` _also_ returns an empty slice, which is likely what's happening here. I'll try and fix that.

In the meantime, do you have a Regal config file in your project workspace? I suppose that if Regal finds one, it won't keep searching, which could be a workaround in the meantime. Just create a `.regal/config.yaml` file in your project root directory, and put something in there: https://github.com/styraInc/regal?tab=readme-ov-file#configuration

Let me know if that helps work around the issue for the time being.

**Comment by anderseknert** [comment]
Btw, @scoop96, what does the path to your workspace look like? Just curious if there's anything in that (like special characters, whitespace, etc) that could cause issues here.

**Comment by scoop96** [comment]
First i started without config file, after so i added a config file (default one as indicated here in de [official doc](https://docs.styra.com/regal#configuration))  

Im adding it again empty, allow me to clean something and I show you the workspace directory

**Comment by scoop96** [comment]
Here is my workspace
![image](https://github.com/StyraInc/regal/assets/19154725/c1bad901-9684-4997-9071-3c9a05d46123)

Here is the URL path
![image](https://github.com/StyraInc/regal/assets/19154725/8dbf34bf-942f-4580-a835-015b1945932b)


And as indicated in the origin, opa and regal are inside of /Users/SE99236/

**Comment by scoop96** [comment]
> Did adding a config file help stop the server from crashing?
> 
> Just to clarify, I don't need to know what your workspace looks like, only what the _path_ to the workspace looks like. I.e. something like `C:\Foo\Bar\Baz`

Nope, its still the same output


![image](https://github.com/StyraInc/regal/assets/19154725/2f9ccc18-0fff-4bad-b151-7d541d174afe)

**Comment by scoop96** [comment]
In my OS, we need to ask for a superior team to give us admin permissions.

Does the OPA extension need them? in order to do that configuration manually myself.

**Comment by anderseknert** [comment]
No, no admin permissions needed 🙂 Thank you for all the details provided! I'm still not sure what would cause this, and I don't have a windows machine at hand, but I'll try my best to see if I can reproduce this in some way. I'll keep you posted!

**Comment by scoop96** [comment]
After the commit, i updated the .exe and the issue still on same thing

**Comment by anderseknert** [comment]
Did you build Regal yourself? If not, you'll have to get the v0.21.2 release from here: https://github.com/StyraInc/regal/releases/tag/v0.21.2

**Comment by scoop96** [comment]
The first download was wrong, after using the v0.21.2 the error still on, that is odd am i right?

In the new error the comment `Server process exited with code 2.` its in a different possition


```
panic: runtime error: index out of range [0] with length 0

goroutine 35 [running]:
github.com/styrainc/regal/pkg/config.FindRegalDirectory({0xc0004025a1, 0x1d})
	/home/runner/work/regal/regal/pkg/config/config.go:144 +0x497
github.com/styrainc/regal/pkg/config.FindConfig({0xc0004025a1?, 0xc0004281e0?})
	/home/runner/work/regal/regal/pkg/config/config.go:153 +0x1c
github.com/styrainc/regal/internal/lsp.(*LanguageServer).handleInitialize(0xc00011ce00, {0x140?, 0x9a2220?}, 0xc00018e3b0?, 0xc00041e000)
	/home/runner/work/regal/regal/internal/lsp/server.go:1024 +0x517
github.com/styrainc/regal/internal/lsp.(*LanguageServer).Handle(0xc00011ce00, {0xf6f388, 0xc00037ce60}, 0xc0000db320, 0xc00041e000)
	/home/runner/work/regal/regal/internal/lsp/server.go:102 +0x191
github.com/sourcegraph/jsonrpc2.(*HandlerWithErrorConfigurer).Handle(0xc00038a1e0, {0xf6f388, 0xc00037ce60}, 0xc0000db320, 0xc00041e000)
	/home/runner/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.2.0/handler_with_error.go:21 +0x57
github.com/sourcegraph/jsonrpc2.(*Conn).readMessages(0xc0000db320, {0xf6f388, 0xc00037ce60})
	/home/runner/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.2.0/conn.go:205 +0x2dd
created by github.com/sourcegraph/jsonrpc2.NewConn in goroutine 1
	/home/runner/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.2.0/conn.go:62 +0x1e6
[Error - 4:50:08 PM] Server process exited with code 2.
[Error - 4:50:08 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:50:08 PM] Connection to server got closed. Server will not be restarted.
[Error - 4:50:08 PM] Regal LSP client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 

```

**Comment by anderseknert** [comment]
Hmm yeah. I'll need a Windows machine to test this on. I'll get back to you when I have that!

**Comment by srenatus** [comment]
The added check wasn't enough. We'd need to error out if the length is not greater than 1. It's len=1 here, then we drop a segment, it's empty, and accessing the first element panicks...

**Comment by anderseknert** [comment]
@srenatus yep, that's what we get for patching without being able to test properly, I suppose 🤦 

Do you have time to submit a fix? I'm in meetings for the next 2 hours. I'll get another patch release out later tonight.

**Comment by srenatus** [comment]
No way, I'm on the playground 😅

**Comment by anderseknert** [comment]
Lol, alright! I'll need a reviewer anyway, so let's push it out tomorrow.

**Comment by anderseknert** [comment]
@scoop96 can you try v0.23.3? It'll likely won't find your config (but if it does, let me know!) but at least it shouldn't panic.

**Comment by scoop96** [comment]
@anderseknert  This is the new error output:

`2024/04/29 08:46:00 jsonrpc2 handler: notification "$/setTrace" handling error: jsonrpc2: code -32601 message: method not supported: $/setTrace`

**Comment by anderseknert** [comment]
That’s fine. We don’t support that method yet, so we log that when we receive a request for that. It shouldn’t have any impact on server operations though. Are things working? But config file ignored?

**Comment by scoop96** [comment]
I was setting it up but seems like the problems tab started working finally. (very new with OPA-Rego)

Thank you so much I do guess (if in a few days i dont drop by this bug is for real solved) 


Thank you :)
