### ISSUE TITLE
Completions: provide suggestions at the start of a new expression in rule body

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#748]
```rego
allow if {
    |
}
```

If the caret is at the start of a new expression in a rule body, it would be great to see suggestions for built-in functions or references. If I want to say something like "startwith" currently, it'll only be suggested if I first create an assignment:

```rego
allow if {
    x :=|
}
```

But that's obviously not always what you want.

**Comment by charlieegan3** [comment]
This change in https://github.com/StyraInc/regal/pull/763/files#diff-794551c4096e8664cbf5088cbeee28fbced2d388f737f90b0b8e9e6f78847762R28 in #763 also fixed this one.
