### ISSUE TITLE
Completions: let dot (.) stop sugggestions that aren't possible

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#749]
I think it would be good if we used `.` as a delimiter to narrow down suggestions that are only valid with the dot present. Consider this:

![Screenshot 2024-05-27 at 13 34 56](https://github.com/StyraInc/regal/assets/510711/0c231133-4260-402a-9796-e89c98e7f438)

In that case, the suggestions seen should all be there when the user types `config`, but once they type `config.` the suggestions should all be for refs under the `config` tree, and `config_test.xxx` suggestions should dissappear from the list.

**Comment by charlieegan3** [comment]
I think that this is fixed in #763


https://github.com/StyraInc/regal/assets/1774239/0c39127a-e1c8-45fc-b770-5223aa5e40b9
