### ISSUE TITLE
Completions: don't suggest refs from ignored files

### ISSUE THREAD

**Issue by charlieegan3** [StyraInc/regal#766]
We will likely want to do this in the completions providers rather than in the indexing of refs since the refs might be handy for other things.

![image](https://github.com/StyraInc/regal/assets/1774239/dc63fd33-b542-4aad-8918-4c3d693afed1)

**Comment by charlieegan3** [comment]
I feel like this is a trickier one, do we want to handle the case where a user can ignore linting but still wants completions?

I guess that [ignoring files globally](https://docs.styra.com/regal#ignoring-files-globally) makes sense to follow if we update the docs to explain these will be ignored by completions in the language server too?

**Comment by anderseknert** [comment]
If you want to disable the linter, do that by disabling all rules rather than ignoring files:

```yaml
rules:
  default:
    level: ignor
```

That'll give you no linting with all files still included by the language server for completions and whatnot. But yeah, making that clear in the docs if it isn't would be good!
