### ISSUE TITLE
Log warning to Stderror when Regal is outdated

### ISSUE THREAD

**Issue by charlieegan3** [StyraInc/regal#802]
Regal should log to stderr if it checks the latest releases and determines that its version is not the latest. This should not happen in development builds.

**Comment by anderseknert** [comment]
👍 Are you thinking we should do this for the `language-server` command only, or also for `regal lint`, et. al? 

Although we wouldn't collect any data as part of this, it could easily be considered "telemetry", and we'd need to take that into consideration. To make that as non-intrusive as possible, I'd imagine we'd at least want to consider:

1. Request is made async, and should have minimal performance impact
1. If offline / request fails, do nothing / print nothing
1. Should be possible to opt-out (via config or env var) 
1. Document this and be very clear about what's sent and for what purpose (i.e not really "telemetry")
1. Bonus points if possible to direct the check to your own backend, to be able to coordinate updates for your org 

I guess one other option to consider is something more primitive, like to simply include "build date" timestamp in the binary, and then log the warning if current time is > 2-3 months past that, or something? Downside obviously being that users could run weeks, or even months, on an old release before being notified. And of course the fact that we'd need to make frequent releases 😅 But that's not been a problem so far.
