### ISSUE TITLE
CI: See if we can use caching to avoid downloading rq over and over

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#818]
Most builds spend 30-60 seconds downloading rq. Since it won't change frequently, it would be good if we could cache the result of the download and not do it again if the binary exists from before.

![Uploading Screenshot 2024-06-10 at 15.38.12.png…]()

**Comment by charlieegan3** [comment]
Hmm

<img width="1314" alt="Screenshot 2024-06-10 at 14 50 40" src="https://github.com/StyraInc/regal/assets/1774239/d76ba261-e66c-45b4-ba9b-3260799cd8dc">


<img width="1353" alt="Screenshot 2024-06-10 at 15 06 56" src="https://github.com/StyraInc/regal/assets/1774239/97bb7e67-c5c8-43d9-92f3-1c3794fe4c66">

I guess that sometimes it was taking much longer so this seems to make sense anyway
