### ISSUE TITLE
Code completion in comments (Zed)

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#826]
For some reason, Zed seems to give code completion inside of comments. We should investigate why that differs from VS Code, where I don't seem to be able to reproduce this.

<img width="815" alt="Screenshot 2024-06-12 at 14 14 56" src="https://github.com/StyraInc/regal/assets/510711/f45e1022-188a-4de4-820b-172d4daad9a3">

**Comment by srenatus** [comment]
https://github.com/zed-industries/zed/issues/6694

**Comment by anderseknert** [comment]
Thanks @srenatus! That's helpful. Even if it's a bug in Zed, I think we can detect the context is a comment, and simply not return any suggestions. @charlieegan3 ?
