### ISSUE TITLE
Diagnostics reported remains after branch change where file doesn't exist

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#857]
Creating "foo.rego" and deleting it doesn't seem to remove the diagnostics reported for that file.

<img width="778" alt="Screenshot 2024-06-20 at 07 05 42" src="https://github.com/StyraInc/regal/assets/510711/ace12f59-590a-4920-a51a-46a9399514f9">

**Comment by charlieegan3** [comment]
I _was_ able to replicate this but now I can't. Do you remember anything you had in this env to make it happen?

**Comment by anderseknert** [comment]
No, seems to have been accidentally fixed somehow 😅 But I'll take it! Let's close and re-open if we encounter this again.

**Comment by charlieegan3** [comment]
Hmm, this is hard as in this case the client didn't delete the file. (aka right click, delete).

I'd be interested to know what other language servers do here, but doing a full reload on branch change seems reasonable.

**Comment by anderseknert** [comment]
Yeah... there's probably a branch change listener somewhere in the client already, but ideally we'd be able to catch this without relying on client code 🤔 we could perhaps just check periodically, but if there's a better way, that'd be good.

**Comment by charlieegan3** [comment]
Some notes from my working on this.

FS Notify can't operate in a recursive way. If you want to watch new files added to new dirs then you need to introduce some polling based delay to get the file state should you miss the initial file creation event.

Other language servers seem to still use this approach, e.g. https://github.com/golang/tools/blob/55d718e5dba2aaaa12d0a2ab2c11c7ac7eb84fcb/gopls/internal/cache/snapshot.go, but I was unable to write a test that reliably passed without introducing a delay. Some WIP on that here: https://github.com/StyraInc/regal/commit/f0bce94ebb5ab7c2daa38bd2ed8b469409bffee7

I opted to keep it really simple for now and circle back if we still have other issues.

One additional challenge here is that you can't 'just' load the changed contents from disk as there might be unsaved changes in an open buffer. So even my polling implementation misses files that are changed outwith the client. I am unsure how to address this particular issue even with an event based approach.

It might be best to open a new issue for this specifically? (changes files behind open buffers)
